### ISSUE TITLE
Ecommerce Simulation Orders Table

### ISSUE THREAD

**Issue by larryzli** [DevMountain/sql-2-afternoon#10]
The way that it is currently worded makes it seem like every order can only have 1 product. 

Current Wording:
> * Users need a name and an email.
> * Products need a name and a price
> * Orders need a ref to product.
> * All 3 need primary keys.

Since orders can contain multiple products, orders should be a reference table between products and users (many-to-many) and therefore does not need a primary key, just an order_number column that does not need to be unique. I'm assuming this based on the queries it wants you to call after creating the tables:

Current Requested Queries:
> * Run queries against your data.
>   * Get all products for the first order.
>   * Get all orders.
>   * Get the total cost of an order ( sum the price of all products on an order ).

Should probably also update wording to add multiple items to each order when creating orders or the queries that you run after do not make much sense if each order only contains 1 item.

Current Wording:
> * Add some data to fill up each table.
>   * At least 3 users, 3 products, 3 orders.

**Comment by josectobar** [comment]
I agree, this instructions are confusing and do not make sense when trying to generate a foreign key between users and orders. It says that orders need to have a primary key and the relationship between orders and products is many to many....
